#!/usr/bin/env php
<?php
declare(strict_types=1);

use Ollieread\MMO\WS\Game;
use Ratchet\Http\HttpServer;
use Ratchet\Server\IoServer;
use Ratchet\WebSocket\WsServer;
use React\EventLoop\Factory;
use React\Socket\Server;

require __DIR__ . '/vendor/autoload.php';

$loop = Factory::create();

$socket = new Server('0.0.0.0:8080', $loop);
$server = new IoServer(new HttpServer(new WsServer(Game::instance())), $socket, $loop);

$server->run();